class TOR_KEYS:
    S_USER_AGENT = "User-Agent"
    S_HTTP = "http"
    S_HTTPS = "https"


class REDIS_KEYS:
    S_NETWORK_MONITOR_STATUS = "S_NETWORK_MONITOR_STATUS"
    S_RAW_HOST_HTML = "S_RAW_HOST_HTML_V1"
